version: "3"
services:
  auth:
    image: jboss/keycloak:9.0.0
    environment:
      - DB_ADDR=db
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DB_VENDOR=postgres
    ports:
      - "8080:8080"
    volumes:
      - "./auth-server/configuration/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml"
      - "./auth-server/themes/custom-theme:/opt/jboss/keycloak/themes/custom-theme"

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata: