version: "3"
services:
  auth:
    image: jboss/keycloak:9.0.0
    environment:
      - DB_ADDR=db
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DB_VENDOR=postgres
      # https://hub.docker.com/r/jboss/keycloak
      - KEYCLOAK_STATISTICS=on
    ports:
      - "8080:8080"
    volumes:
      - "./auth-server/configuration/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml"
      - "./auth-server/themes/custom-theme:/opt/jboss/keycloak/themes/custom-theme"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - "db_data:/var/lib/postgresql/data"

  consul:
    image: consul:1.7.1
    ports:
      - "8500:8500"
    volumes:
      - "./consul/config:/consul/config"

#  zookeeper:
#    image: bitnami/zookeeper:3
#    environment:
#      - ZOO_ENABLE_AUTH=yes
#      - ZOO_CLIENT_USER=user
#      - ZOO_CLIENT_PASSWORD=password
#    volumes:
#      - "zookeeper_data:/bitnami/zookeeper"
#
#  kafka:
#    image: bitnami/kafka:2
#    ports:
#      - '9092:9092'
#    volumes:
#      - 'kafka_data:/bitnami/kafka'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ZOOKEEPER_USER=user
#      - KAFKA_ZOOKEEPER_PASSWORD=password
#      - KAFKA_BROKER_USER=user
#      - KAFKA_BROKER_PASSWORD=password
#    depends_on:
#      - zookeeper

volumes:
  db_data:
#  kafka_data:
#  zookeeper_data: