version: "3"
services:
  auth:
    image: jboss/keycloak:9.0.2
    environment:
      - DB_ADDR=db
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DB_VENDOR=postgres
      # https://hub.docker.com/r/jboss/keycloak
      # Section: Enable some metrics
      - KEYCLOAK_STATISTICS=on
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - "./auth-server/configuration/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml"
      - "./auth-server/themes/custom-theme:/opt/jboss/keycloak/themes/custom-theme"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - "db_data:/var/lib/postgresql/data"

  consul:
    image: consul:1.7.1
    ports:
      - "8500:8500"
    volumes:
      - "./consul/config:/consul/config"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  db_data:
  rabbitmq_data:
